name: Delete Old ECR Images

on:
  schedule:
    - cron: '0 0 * * 0' # This will run every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  delete-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repository URI
        run: echo "ECR_REPOSITORY_URI=992382854711.dkr.ecr.eu-north-1.amazonaws.com/dummy-images-repo" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List ECR Images
        id: list_images
        run: |
          echo "Fetching images from ECR..."
          images=$(aws ecr list-images --repository-name ${ECR_REPOSITORY_URI##*/} --query 'imageIds[*].imageTag' --output text | tr '\t' '\n')
          echo "Images fetched: $images"
          echo "images=$images" >> $GITHUB_ENV

      - name: Delete Old Images
        run: |
          images=(${{ env.images }})
          num_images=${#images[@]}
          keep=4

          if (( num_images > keep )); then
              echo "Deleting old images..."
              images_to_delete=(${images[@]:keep})
              for image in "${images_to_delete[@]}"; do
                  echo "Deleting image: $image"
                  aws ecr batch-delete-image --repository-name ${ECR_REPOSITORY_URI##*/} --image-ids imageTag=$image
              done
          else
              echo "No images to delete. Keeping all $num_images images."
          fi
